// Pre-extracted passages bundled with the app. Generated by
// `npm run build:passages` (see scripts/build-passages.mjs). Shipping these
// statically means quiz load time is ~zero — no Gutenberg fetches at runtime.

import passagesJson from "@/data/passages.json";

export interface CachedPassage {
  passage: string;
  bookId: number;
  bookTitle: string | null;
}

const CACHE: Record<string, CachedPassage[]> = passagesJson as Record<
  string,
  CachedPassage[]
>;

export function getCachedPassage(thinkerId: string): CachedPassage | null {
  const list = CACHE[thinkerId];
  if (!list || list.length === 0) return null;
  return list[Math.floor(Math.random() * list.length)];
}

export function getCachedThinkerIds(): string[] {
  return Object.keys(CACHE).filter((id) => CACHE[id]?.length > 0);
}
