import { SCHOOLS, type School, getSchoolById } from "./schools";

export type Era =
  | "ancient"
  | "medieval"
  | "early-modern"
  | "enlightenment"
  | "19th-century"
  | "20th-century";

export type Form =
  | "treatise"
  | "dialogue"
  | "aphorism"
  | "essay"
  | "letters"
  | "meditation";

export interface Thinker {
  id: string;
  name: string;
  school: string;
  era: Era;
  birthYear: number; // BCE is negative
  deathYear: number | null;
  nationality: string;
  bio: string;
  // 4-6 dense one-line summaries of the ideas this thinker is famous for.
  // Always shown on the reveal screen — the educational core of the app.
  keyTakeaways: string[];
  // 4-6 short, prompt-form statements ("God is dead.") used as the question
  // in Takeaway-mode quizzes. The user reads one and guesses the thinker.
  takeawayPrompts: string[];
  // Project Gutenberg book IDs for passage-mode quizzes. If empty, this
  // thinker only appears in takeaway-mode.
  gutenbergIds: number[];
  // Display hint for the passage card.
  form: Form;
  // 2-5 famous works for display on the thinker page.
  keyWorks: string[];
}

export const THINKERS: Thinker[] = [
  // ============ Pre-Socratic ============
  {
    id: "heraclitus",
    name: "Heraclitus",
    school: "pre-socratic",
    era: "ancient",
    birthYear: -535,
    deathYear: -475,
    nationality: "Greek (Ephesus)",
    bio: "The 'obscure' philosopher of flux, who wrote in dense fragments and held that the underlying logos of the world is fire — constant change.",
    keyTakeaways: [
      "Everything flows — you cannot step into the same river twice.",
      "Opposites are united in tension: the bow only works because string and wood pull against each other.",
      "The underlying order of the cosmos is a divine logos, accessible to reason but hidden from the lazy.",
      "Strife (polemos) is the father of all things; harmony is the resolution of opposites, not their absence.",
    ],
    takeawayPrompts: [
      "You cannot step twice into the same river.",
      "The path up and the path down are one and the same.",
      "War is the father of all and king of all.",
      "Character is destiny.",
    ],
    gutenbergIds: [],
    form: "aphorism",
    keyWorks: ["On Nature (surviving fragments)"],
  },
  {
    id: "parmenides",
    name: "Parmenides",
    school: "pre-socratic",
    era: "ancient",
    birthYear: -515,
    deathYear: -450,
    nationality: "Greek (Elea)",
    bio: "Elean poet-philosopher who argued, in a hexameter poem of breathtaking severity, that change and plurality are illusions and that Being is one, unchanging, and complete.",
    keyTakeaways: [
      "Being is, and non-being is not — there is no middle ground.",
      "Change is impossible: what is cannot come from what is not.",
      "The senses deceive us; only reason can grasp reality.",
      "What truly exists is one, eternal, indivisible, and motionless.",
    ],
    takeawayPrompts: [
      "Being is, and non-being is not.",
      "What is, is uncreated and indestructible.",
      "Thinking and being are the same.",
      "The way of truth and the way of opinion must not be confused.",
    ],
    gutenbergIds: [],
    form: "aphorism",
    keyWorks: ["On Nature (surviving fragments)"],
  },
  {
    id: "pythagoras",
    name: "Pythagoras",
    school: "pre-socratic",
    era: "ancient",
    birthYear: -570,
    deathYear: -495,
    nationality: "Greek (Samos)",
    bio: "Mathematician-mystic who founded a religious-philosophical brotherhood in southern Italy and taught that number is the deep structure of reality.",
    keyTakeaways: [
      "Number is the substance of all things — reality has a mathematical structure.",
      "The soul is immortal and transmigrates from body to body across lives.",
      "Philosophy is a discipline of purification, requiring strict dietary and behavioural rules.",
      "Musical harmony reveals the same ratios that govern the heavens (the 'music of the spheres').",
    ],
    takeawayPrompts: [
      "All is number.",
      "The soul transmigrates from one body to the next.",
      "Reduce yourself to silence and the truth will appear.",
      "The cosmos sings in mathematical ratios.",
    ],
    gutenbergIds: [],
    form: "aphorism",
    keyWorks: ["Teachings preserved by later Pythagoreans"],
  },
  {
    id: "democritus",
    name: "Democritus",
    school: "pre-socratic",
    era: "ancient",
    birthYear: -460,
    deathYear: -370,
    nationality: "Greek (Abdera)",
    bio: "The 'laughing philosopher' who, with his teacher Leucippus, proposed that all of reality is composed of indivisible particles ('atoms') moving through empty space ('the void').",
    keyTakeaways: [
      "Nothing exists except atoms and the void; everything else is opinion.",
      "Atoms differ only in shape, size, and arrangement — colour, taste, and warmth are how we perceive them, not what they are.",
      "There is no purpose in nature, only necessity — atoms collide and the world results.",
      "The good life is cheerfulness (euthymia) — a steady, untroubled state of soul.",
    ],
    takeawayPrompts: [
      "Nothing exists except atoms and the void.",
      "By convention sweet, by convention bitter — in reality, atoms and void.",
      "Everything happens by necessity, nothing by chance.",
      "The cheerful soul lives best.",
    ],
    gutenbergIds: [],
    form: "aphorism",
    keyWorks: ["Fragments preserved by Aristotle and later writers"],
  },

  // ============ Platonism ============
  {
    id: "socrates",
    name: "Socrates",
    school: "platonism",
    era: "ancient",
    birthYear: -470,
    deathYear: -399,
    nationality: "Greek (Athens)",
    bio: "Athenian stonecutter who wrote nothing but, through endless public questioning, made philosophy a way of life — and was executed for it. Almost everything we know about him comes through Plato.",
    keyTakeaways: [
      "I know that I know nothing — wisdom begins with the recognition of one's own ignorance.",
      "The unexamined life is not worth living.",
      "No one does wrong willingly: vice is a kind of ignorance, virtue a kind of knowledge.",
      "Care for your soul more than for your body or your possessions.",
    ],
    takeawayPrompts: [
      "The unexamined life is not worth living.",
      "I know that I know nothing.",
      "No one does evil knowingly.",
      "Care for your soul before your purse.",
    ],
    gutenbergIds: [1656, 1726],
    form: "dialogue",
    keyWorks: ["Apology", "Crito", "Phaedo (all by Plato)"],
  },
  {
    id: "plato",
    name: "Plato",
    school: "platonism",
    era: "ancient",
    birthYear: -428,
    deathYear: -348,
    nationality: "Greek (Athens)",
    bio: "Aristocratic Athenian student of Socrates and teacher of Aristotle, who founded the Academy and wrote ~35 surviving dialogues that, between them, posed almost every question Western philosophy has since tried to answer.",
    keyTakeaways: [
      "What is truly real are unchanging Forms (Justice itself, Beauty itself); the visible world is their shadow.",
      "True knowledge is recollection — the soul remembers what it knew before it was born.",
      "The soul has three parts: reason, spirit, and appetite — and the just person rules each in its proper order.",
      "The ideal city is ruled by philosopher-kings, who alone have escaped the cave of ordinary opinion.",
      "Knowledge cannot finally be written down: the deepest truths pass only between minds in living conversation.",
    ],
    takeawayPrompts: [
      "The visible world is a shadow of the eternal world of Forms.",
      "True knowledge is recollection.",
      "Until philosophers rule, cities will have no rest from their evils.",
      "Justice in the soul is each part doing its proper work.",
      "Only the philosopher escapes the cave — and must return to teach the others.",
    ],
    gutenbergIds: [1497, 1635, 1726, 1656, 1572, 1600, 1750, 1635],
    form: "dialogue",
    keyWorks: ["The Republic", "Symposium", "Phaedo", "Apology", "Phaedrus"],
  },

  // ============ Aristotelianism ============
  {
    id: "aristotle",
    name: "Aristotle",
    school: "aristotelianism",
    era: "ancient",
    birthYear: -384,
    deathYear: -322,
    nationality: "Greek (Stagira)",
    bio: "Twenty-year student of Plato, tutor to Alexander the Great, and founder of the Lyceum, whose surviving lecture notes cover logic, physics, biology, ethics, politics, rhetoric, and the philosophy of being — and shaped Western thought for two millennia.",
    keyTakeaways: [
      "Happiness (eudaimonia) is activity of the soul in accordance with virtue, performed over a complete life.",
      "Virtue is a mean between two extremes, learned by habit — neither too rash nor too cowardly, neither stingy nor wasteful.",
      "Everything in nature has four causes: material, formal, efficient, and final.",
      "Humans are by nature political animals — we can only fully realise ourselves in a polis.",
      "There must be an Unmoved Mover that is itself unchanging but the source of all motion.",
    ],
    takeawayPrompts: [
      "Happiness is activity of the soul in accordance with virtue.",
      "Virtue is a mean between two extremes.",
      "Man is by nature a political animal.",
      "We are what we repeatedly do; excellence is a habit.",
      "Every motion in the world depends on an unmoved mover.",
    ],
    gutenbergIds: [8438, 6762, 26095, 1974],
    form: "treatise",
    keyWorks: [
      "Nicomachean Ethics",
      "Politics",
      "Metaphysics",
      "Poetics",
      "On the Soul",
    ],
  },

  // ============ Stoicism ============
  {
    id: "epictetus",
    name: "Epictetus",
    school: "stoicism",
    era: "ancient",
    birthYear: 50,
    deathYear: 135,
    nationality: "Greek (Roman slave, later freedman)",
    bio: "Born a slave, lamed by his master, freed and exiled by the emperor — Epictetus founded a school in Nicopolis whose teachings, written down by his pupil Arrian, became the most-quoted handbook of practical Stoicism.",
    keyTakeaways: [
      "Some things are up to us (our judgments, desires, aversions) and some things are not (our body, reputation, possessions) — confine your care to the first.",
      "It is not events that disturb us, but our judgments about events.",
      "Wish for things to be as they are, and you will be free.",
      "Do not say of anything: 'I have lost it.' Say: 'I have given it back.'",
    ],
    takeawayPrompts: [
      "Some things are in our control, and others are not.",
      "It is not events that disturb us, but our judgments about them.",
      "Don't ask the world to be what you want; want what the world gives you.",
      "If you would be a philosopher, expect to be laughed at.",
    ],
    gutenbergIds: [45109, 871, 10661],
    form: "letters",
    keyWorks: ["Discourses", "Enchiridion (Handbook)"],
  },
  {
    id: "seneca",
    name: "Seneca",
    school: "stoicism",
    era: "ancient",
    birthYear: -4,
    deathYear: 65,
    nationality: "Roman (Hispania)",
    bio: "Playwright, tutor to the young Nero, immensely rich and immensely uncomfortable about it, whose 124 surviving Letters to Lucilius are the most readable extant Stoic prose. Ordered to commit suicide by Nero in 65 CE.",
    keyTakeaways: [
      "Life is long if you know how to use it — most people are too busy living to live.",
      "Cease to hope, and you will cease to fear.",
      "We suffer more in imagination than in reality.",
      "Retire into yourself as much as possible; associate with those who will make you better.",
      "Begin at once to live, and count each separate day as a separate life.",
    ],
    takeawayPrompts: [
      "We suffer more in imagination than in reality.",
      "Cease to hope, and you will cease to fear.",
      "Life is long if you know how to use it.",
      "Begin at once to live, and count each day as a separate life.",
    ],
    gutenbergIds: [56075, 56079, 8732, 3794],
    form: "letters",
    keyWorks: [
      "Letters from a Stoic",
      "On the Shortness of Life",
      "On Anger",
      "On the Tranquility of Mind",
    ],
  },
  {
    id: "marcus-aurelius",
    name: "Marcus Aurelius",
    school: "stoicism",
    era: "ancient",
    birthYear: 121,
    deathYear: 180,
    nationality: "Roman",
    bio: "Roman emperor for nearly twenty years, mostly spent fighting on the Danube frontier. His private notebook, never intended for publication, is the only surviving extended meditation by a sitting Stoic monarch.",
    keyTakeaways: [
      "You have power over your mind — not outside events. Realise this, and you will find strength.",
      "Confine yourself to the present.",
      "The impediment to action advances action. What stands in the way becomes the way.",
      "Waste no more time arguing what a good man should be. Be one.",
      "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.",
    ],
    takeawayPrompts: [
      "You have power over your mind — not outside events.",
      "The impediment to action advances action.",
      "Confine yourself to the present.",
      "Waste no more time arguing what a good man should be. Be one.",
      "Soon you will have forgotten the world, and soon the world will have forgotten you.",
    ],
    gutenbergIds: [2680, 55317],
    form: "meditation",
    keyWorks: ["Meditations"],
  },

  // ============ Epicureanism ============
  {
    id: "epicurus",
    name: "Epicurus",
    school: "epicureanism",
    era: "ancient",
    birthYear: -341,
    deathYear: -270,
    nationality: "Greek (Samos)",
    bio: "Founder of a school in Athens called The Garden — radically inclusive for its time — whose ethics of measured pleasure has been distorted ever since into the very gluttony he opposed. Most of his writings are lost; only three letters and a set of maxims survive.",
    keyTakeaways: [
      "The aim of life is pleasure — properly understood as the absence of bodily pain and mental disturbance.",
      "Death is nothing to us: when we exist, death is not present; when death is present, we do not exist.",
      "The gods, if they exist, take no interest in human affairs — so do not fear them.",
      "Cultivate friendship; eat simply; avoid politics; live unnoticed.",
      "Natural and necessary desires (food, shelter, friendship) are easy to satisfy; unnatural desires (wealth, fame, power) are infinite and miserable.",
    ],
    takeawayPrompts: [
      "Death is nothing to us.",
      "The pleasant life cannot exist without the wise, noble, and just life.",
      "Live unnoticed.",
      "Of all the things wisdom acquires for living well, the greatest is friendship.",
    ],
    gutenbergIds: [],
    form: "letters",
    keyWorks: [
      "Letter to Menoeceus",
      "Letter to Herodotus",
      "Principal Doctrines",
    ],
  },
  {
    id: "lucretius",
    name: "Lucretius",
    school: "epicureanism",
    era: "ancient",
    birthYear: -99,
    deathYear: -55,
    nationality: "Roman",
    bio: "Roman poet about whom almost nothing biographical is known, whose six-book Latin hexameter poem 'De Rerum Natura' is the single greatest extended exposition of Epicurean philosophy — rediscovered in 1417, it helped detonate the Renaissance.",
    keyTakeaways: [
      "All that exists is atoms moving in empty space — there is no purpose in nature, only causation.",
      "Religion has produced more evil than it has prevented; fear of the gods is the source of much human misery.",
      "The soul is material and perishes with the body; therefore death cannot harm us.",
      "Mind your appetites: nature requires little — vain desire much.",
      "All things wax and wane in their season; nothing in the cosmos lasts forever.",
    ],
    takeawayPrompts: [
      "All that exists is atoms moving in empty space.",
      "So great are the evils that religion has been able to inspire.",
      "Nothing in the cosmos lasts forever; all things wax and wane.",
      "What is food to one man is bitter poison to others.",
    ],
    gutenbergIds: [785],
    form: "treatise",
    keyWorks: ["On the Nature of Things"],
  },

  // ============ Skepticism & Cynicism ============
  {
    id: "diogenes",
    name: "Diogenes of Sinope",
    school: "skepticism",
    era: "ancient",
    birthYear: -412,
    deathYear: -323,
    nationality: "Greek (Sinope, then Athens)",
    bio: "Founding Cynic, lived in a wine barrel, masturbated in public, urinated on dinner guests, and told Alexander the Great to step out of his sunlight. We have no writings — only the anecdotes recorded by Diogenes Laertius and others.",
    keyTakeaways: [
      "Convention is the enemy of virtue: civilisation has made us soft, dishonest, and miserable.",
      "Live in accordance with nature — eat when hungry, sleep when tired, own nothing you cannot carry.",
      "Speak the truth without regard to consequences; the philosopher must be a shameless watchdog (kyon, 'dog').",
      "Wealth, status, and fame are not goods — they are the source of more anxiety than the poverty they pretend to cure.",
    ],
    takeawayPrompts: [
      "Stand a little out of my sunlight.",
      "I am a citizen of the world.",
      "The most beautiful thing in the world is freedom of speech.",
      "I am looking for an honest man.",
    ],
    gutenbergIds: [],
    form: "aphorism",
    keyWorks: ["Sayings preserved by Diogenes Laertius"],
  },
  {
    id: "sextus-empiricus",
    name: "Sextus Empiricus",
    school: "skepticism",
    era: "ancient",
    birthYear: 160,
    deathYear: 210,
    nationality: "Greek (Roman empire)",
    bio: "Physician and the last great Greek Skeptic, whose 'Outlines of Pyrrhonism' is our main surviving systematic statement of ancient Skepticism. His three-stage method — opposition of arguments, suspension of judgment, tranquillity — was rediscovered by Montaigne and Hume.",
    keyTakeaways: [
      "For every argument there is an equally strong opposing argument — so suspend judgment.",
      "Suspension of judgment (epoché) is the path to tranquillity (ataraxia).",
      "Skepticism is not a doctrine but a practice — the Skeptic claims nothing, not even Skepticism.",
      "Live by appearances and local custom, since nothing more certain is available.",
    ],
    takeawayPrompts: [
      "For every argument an equally strong opposing argument can be found.",
      "Suspend judgment and tranquillity will follow.",
      "I assert nothing — not even that I assert nothing.",
      "Live by appearances and custom, since certainty is denied us.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: ["Outlines of Pyrrhonism", "Against the Mathematicians"],
  },

  // ============ Neoplatonism ============
  {
    id: "plotinus",
    name: "Plotinus",
    school: "neoplatonism",
    era: "ancient",
    birthYear: 204,
    deathYear: 270,
    nationality: "Greek-Egyptian (Roman empire)",
    bio: "Lectured in third-century Rome to an audience that included senators. His pupil Porphyry edited the lectures into the 'Enneads' — fifty-four treatises that became the foundation of every subsequent mystical Platonism, Christian, Islamic, and Jewish.",
    keyTakeaways: [
      "Everything that exists emanates from a single ineffable source: the One.",
      "Below the One comes Intellect, which contemplates the Forms; below Intellect, Soul; below Soul, the material world.",
      "The philosophical life is an ascent: turn inward, away from the senses, toward the source from which you came.",
      "Evil is not a substance — it is the absence of being, the receding shadow at the bottom of the chain of emanation.",
      "The highest experience is mystical union with the One — beyond thought, beyond language, beyond self.",
    ],
    takeawayPrompts: [
      "All that exists pours forth from a single ineffable One.",
      "Turn inward — the divine is found in the depths of the soul, not in the world.",
      "Evil is not a substance but a privation of being.",
      "The flight of the alone to the alone.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: ["The Enneads"],
  },

  // ============ Patristic ============
  {
    id: "augustine",
    name: "Augustine of Hippo",
    school: "patristic",
    era: "ancient",
    birthYear: 354,
    deathYear: 430,
    nationality: "Berber-Roman (North Africa)",
    bio: "Manichaean, then sceptic, then Neoplatonist, then converted Christian, then bishop, then author of the most consequential body of theological writing in the Western tradition. His 'Confessions' invented modern interiority; 'City of God' gave Christianity a theology of history.",
    keyTakeaways: [
      "The human heart is restless until it rests in God.",
      "We are not born innocent — original sin corrupts every soul, and only God's grace can save us.",
      "Time exists only in the mind: we measure past as memory, present as attention, future as expectation.",
      "There are two cities — the City of God and the earthly city — woven together throughout history and separated only at the Last Judgment.",
      "Love God and do what you will: the will rightly ordered is the source of all genuine virtue.",
    ],
    takeawayPrompts: [
      "You have made us for yourself, O Lord, and our hearts are restless until they rest in you.",
      "Love, and do what you will.",
      "Time is a distension of the soul.",
      "Two cities have been formed by two loves.",
      "Grant me chastity and self-control — but not yet.",
    ],
    gutenbergIds: [3296, 45304, 14457],
    form: "treatise",
    keyWorks: ["Confessions", "The City of God", "On Christian Doctrine"],
  },
  {
    id: "boethius",
    name: "Boethius",
    school: "patristic",
    era: "medieval",
    birthYear: 477,
    deathYear: 524,
    nationality: "Roman",
    bio: "Roman senator and Christian theologian executed by the Gothic king Theodoric on a charge of treason. Awaiting death he wrote 'The Consolation of Philosophy,' a dialogue between himself and Lady Philosophy that became the schoolbook of the Middle Ages.",
    keyTakeaways: [
      "Fortune is by nature inconstant — to expect her to remain favourable is to misunderstand her.",
      "True happiness cannot lie in goods that can be taken from you.",
      "All things, including evils, work within the providence of God — what looks like fate to us is foreseen by him.",
      "God's foreknowledge does not destroy human freedom, because God sees all time as a single present.",
    ],
    takeawayPrompts: [
      "Fortune turns her wheel with proud and impartial hand.",
      "All fortune is good which serves to instruct, correct, or punish.",
      "Nothing is wretched unless you think it so.",
      "God sees all time as a single eternal present.",
    ],
    gutenbergIds: [14328],
    form: "dialogue",
    keyWorks: ["The Consolation of Philosophy"],
  },

  // ============ Scholasticism ============
  {
    id: "anselm",
    name: "Anselm of Canterbury",
    school: "scholasticism",
    era: "medieval",
    birthYear: 1033,
    deathYear: 1109,
    nationality: "Italian-Norman",
    bio: "Benedictine abbot, later Archbishop of Canterbury, whose 'Proslogion' contains the ontological argument: an a priori proof of God's existence from the very concept of God.",
    keyTakeaways: [
      "Faith seeks understanding — we believe first, then reason about what we believe.",
      "God is 'that than which nothing greater can be thought' — and such a being must exist, since existing is greater than not existing.",
      "Christ's atonement on the cross was necessary to satisfy divine justice: God's honour required it.",
      "Reason illuminates revelation but does not replace it.",
    ],
    takeawayPrompts: [
      "I believe in order that I may understand.",
      "God is that than which nothing greater can be thought.",
      "Faith seeking understanding.",
      "The fool says in his heart, 'There is no God' — but to say it requires the very idea that proves God.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: ["Proslogion", "Monologion", "Cur Deus Homo"],
  },
  {
    id: "aquinas",
    name: "Thomas Aquinas",
    school: "scholasticism",
    era: "medieval",
    birthYear: 1225,
    deathYear: 1274,
    nationality: "Italian",
    bio: "Dominican friar whose vast 'Summa Theologiae' integrated the newly recovered Aristotle with Christian theology so thoroughly that he became — and remains — the canonical philosopher of Catholic thought. Stopped writing months before his death after a mystical experience he called 'so much straw.'",
    keyTakeaways: [
      "There are five ways to demonstrate God's existence: motion, causation, contingency, degrees of perfection, and design.",
      "Reason and faith do not conflict: both come from God; reason can know what God is not, faith reveals what he is.",
      "Natural law is rational creatures' participation in eternal law — there are moral truths accessible to reason alone.",
      "Grace does not destroy nature but perfects it: human virtues are completed, not replaced, by the theological virtues.",
      "Being is convertible with goodness: insofar as anything is, it is good.",
    ],
    takeawayPrompts: [
      "There are five ways to prove the existence of God.",
      "Grace does not destroy nature but perfects it.",
      "Reason can show what God is not; only faith reveals what he is.",
      "Natural law is the rational creature's participation in eternal law.",
      "Beware the man of one book.",
    ],
    gutenbergIds: [17611, 19950],
    form: "treatise",
    keyWorks: ["Summa Theologiae", "Summa Contra Gentiles"],
  },

  // ============ Renaissance Humanism ============
  {
    id: "erasmus",
    name: "Erasmus of Rotterdam",
    school: "renaissance-humanism",
    era: "early-modern",
    birthYear: 1466,
    deathYear: 1536,
    nationality: "Dutch",
    bio: "Northern Renaissance humanist par excellence — a Catholic priest who edited the Greek New Testament, satirised the church without ever leaving it, and corresponded with every important figure of his age.",
    keyTakeaways: [
      "Folly rules the world — and our pretences of seriousness are mostly self-flattery.",
      "True religion is interior and ethical; ritual and dogma have largely supplanted Christ's actual teaching.",
      "Knowledge of the original Greek and Hebrew is the only path to genuine scriptural understanding.",
      "Peace is almost always preferable to war, however just the cause appears.",
    ],
    takeawayPrompts: [
      "In the kingdom of the blind, the one-eyed man is king.",
      "Folly is in fact the very thing that holds society together.",
      "War is sweet to those who have not tried it.",
      "Christ's teaching was simple; we have made it impossibly elaborate.",
    ],
    gutenbergIds: [9371, 30201],
    form: "essay",
    keyWorks: [
      "In Praise of Folly",
      "Handbook of the Christian Soldier",
      "Adagia",
    ],
  },
  {
    id: "machiavelli",
    name: "Niccolò Machiavelli",
    school: "renaissance-humanism",
    era: "early-modern",
    birthYear: 1469,
    deathYear: 1527,
    nationality: "Italian (Florence)",
    bio: "Florentine diplomat exiled when the Medici returned to power, who in unwelcome retirement wrote the founding text of realist political philosophy — 'The Prince,' published posthumously, has been notorious ever since.",
    keyTakeaways: [
      "Politics must be studied as it actually is, not as it ought to be.",
      "It is better for a prince to be feared than loved, if he cannot be both.",
      "A wise ruler keeps his word only when it does not damage him to do so.",
      "Fortune is a woman: bold action is better than caution because she favours the young.",
      "Republics, where they can survive, are more stable and better for their citizens than principalities.",
    ],
    takeawayPrompts: [
      "It is better to be feared than loved, if you cannot be both.",
      "The ends justify the means.",
      "A wise ruler ought never to keep faith when by so doing it would be against his interest.",
      "Fortune is a woman, and it is necessary, if you wish to master her, to conquer her by force.",
    ],
    gutenbergIds: [1232, 10827, 2464],
    form: "treatise",
    keyWorks: ["The Prince", "Discourses on Livy", "The Art of War"],
  },
  {
    id: "montaigne",
    name: "Michel de Montaigne",
    school: "renaissance-humanism",
    era: "early-modern",
    birthYear: 1533,
    deathYear: 1592,
    nationality: "French",
    bio: "Retired French nobleman who, in a tower lined with classical books, invented the personal essay — a hundred-and-seven loosely structured first-person investigations of any topic that occurred to him, conducted with an honesty no earlier writer had dared.",
    keyTakeaways: [
      "What do I know? — every confident assertion deserves to be questioned.",
      "Each man bears the entire form of the human condition; I study myself more than any other subject.",
      "He who fears he shall suffer, already suffers what he fears.",
      "The greatest thing in the world is to know how to belong to oneself.",
      "Custom blinds us — what looks barbarous abroad is no stranger than what is normal at home.",
    ],
    takeawayPrompts: [
      "What do I know?",
      "He who fears he shall suffer, already suffers what he fears.",
      "Each man bears the entire form of the human condition.",
      "The greatest thing in the world is to know how to belong to oneself.",
      "Every man calls barbarous anything he is not accustomed to.",
    ],
    gutenbergIds: [3600, 3601, 3602],
    form: "essay",
    keyWorks: ["Essays"],
  },

  // ============ Rationalism ============
  {
    id: "descartes",
    name: "René Descartes",
    school: "rationalism",
    era: "early-modern",
    birthYear: 1596,
    deathYear: 1650,
    nationality: "French",
    bio: "French soldier-mathematician who, after a series of dreams in a heated room in 1619, set out to rebuild philosophy on the foundation of indubitable certainty. Died of pneumonia in Stockholm tutoring Queen Christina, who insisted on 5am lessons.",
    keyTakeaways: [
      "I think, therefore I am — this is the one truth that cannot be doubted.",
      "Doubt everything that can be doubted; what survives is the foundation of knowledge.",
      "Mind and body are two fundamentally different substances: thinking thing and extended thing.",
      "Clear and distinct ideas are the criterion of certain knowledge — and a non-deceiving God guarantees them.",
      "Animals are sophisticated machines; only humans, possessing reason, have immaterial souls.",
    ],
    takeawayPrompts: [
      "I think, therefore I am.",
      "Doubt everything that can be doubted — what remains is your foundation.",
      "The mind is a thinking thing; the body is an extended thing — they are entirely distinct.",
      "Clear and distinct ideas cannot deceive me, for God is no deceiver.",
    ],
    gutenbergIds: [59, 23306, 25830],
    form: "treatise",
    keyWorks: [
      "Discourse on the Method",
      "Meditations on First Philosophy",
      "Principles of Philosophy",
    ],
  },
  {
    id: "spinoza",
    name: "Baruch Spinoza",
    school: "rationalism",
    era: "early-modern",
    birthYear: 1632,
    deathYear: 1677,
    nationality: "Dutch (Sephardic Jewish)",
    bio: "Amsterdam lens-grinder excommunicated from the Sephardic community at 23, who quietly produced the most logically rigorous metaphysical system in European history. His 'Ethics' is set out in the form of Euclidean geometry: definitions, axioms, propositions, demonstrations.",
    keyTakeaways: [
      "There is only one substance — God or Nature (Deus sive Natura) — and everything that exists is a mode of it.",
      "Mind and body are not two substances but two aspects of the same thing seen under different attributes.",
      "Everything that happens happens necessarily; freedom is the understanding of this necessity, not its absence.",
      "Emotions are confused ideas; we are freed from them by understanding their causes.",
      "The highest human good is the intellectual love of God — adequately knowing reality under the aspect of eternity.",
    ],
    takeawayPrompts: [
      "God, or Nature — Deus sive Natura.",
      "Everything that happens, happens necessarily.",
      "Freedom is the understanding of necessity.",
      "We do not desire something because it is good; we call it good because we desire it.",
      "All things excellent are as difficult as they are rare.",
    ],
    gutenbergIds: [3800, 989, 17000],
    form: "treatise",
    keyWorks: ["Ethics", "Theological-Political Treatise"],
  },
  {
    id: "leibniz",
    name: "Gottfried Wilhelm Leibniz",
    school: "rationalism",
    era: "early-modern",
    birthYear: 1646,
    deathYear: 1716,
    nationality: "German",
    bio: "Universal genius who invented calculus independently of Newton, designed a calculating machine, drafted plans to reunite the Christian churches, served as Hanoverian court librarian, and built a metaphysics in which reality is composed of infinitely many windowless 'monads.'",
    keyTakeaways: [
      "Reality is composed of monads — simple, immaterial, indivisible substances, each mirroring the whole universe from its own perspective.",
      "Monads do not interact; God has pre-established a harmony so that they all unfold in perfect synchrony.",
      "Nothing happens without a sufficient reason — the principle that underlies all rational inquiry.",
      "This is the best of all possible worlds: God, surveying all possibilities, chose to actualise the optimum.",
      "All truths are ultimately analytic — in the complete concept of every individual, all its predicates are already contained.",
    ],
    takeawayPrompts: [
      "This is the best of all possible worlds.",
      "Nothing happens without a sufficient reason.",
      "Monads have no windows through which anything can enter or leave.",
      "Music is the secret arithmetic of the soul, unaware that it counts.",
    ],
    gutenbergIds: [17147],
    form: "treatise",
    keyWorks: ["Monadology", "Discourse on Metaphysics", "Theodicy"],
  },
  {
    id: "pascal",
    name: "Blaise Pascal",
    school: "rationalism",
    era: "early-modern",
    birthYear: 1623,
    deathYear: 1662,
    nationality: "French",
    bio: "Mathematical prodigy who invented projective geometry as a teenager and co-founded probability theory, then experienced a mystical conversion in 1654 and spent his remaining years defending Jansenist Catholicism. The 'Pensées' are scraps of an unfinished apology for Christianity.",
    keyTakeaways: [
      "All of humanity's problems stem from man's inability to sit quietly in a room alone.",
      "Wager on God: if he exists, you gain everything; if not, you lose nothing.",
      "The heart has its reasons, of which reason knows nothing.",
      "We are something and we are not everything — between nothing and infinity, a thinking reed.",
      "The eternal silence of these infinite spaces frightens me.",
    ],
    takeawayPrompts: [
      "The heart has its reasons, of which reason knows nothing.",
      "Wager on God: if he exists, you gain everything; if not, you lose nothing.",
      "Man is but a reed, the weakest in nature, but he is a thinking reed.",
      "All of humanity's problems stem from man's inability to sit quietly in a room alone.",
      "The eternal silence of these infinite spaces frightens me.",
    ],
    gutenbergIds: [18269, 46921],
    form: "aphorism",
    keyWorks: ["Pensées", "Provincial Letters"],
  },

  // ============ Empiricism ============
  {
    id: "bacon",
    name: "Francis Bacon",
    school: "empiricism",
    era: "early-modern",
    birthYear: 1561,
    deathYear: 1626,
    nationality: "English",
    bio: "Lord Chancellor of England, disgraced for taking bribes, who in retirement laid down the manifesto of modern science: knowledge through systematic inductive observation, not deduction from inherited authority.",
    keyTakeaways: [
      "Knowledge is power — and the purpose of science is the relief of man's estate.",
      "Throw out the 'idols' that distort thought: of the tribe, the cave, the marketplace, the theatre.",
      "True science proceeds by induction from carefully observed particulars, not by deducing the world from first principles.",
      "Some books are to be tasted, others to be swallowed, and some few to be chewed and digested.",
    ],
    takeawayPrompts: [
      "Knowledge is power.",
      "If a man will begin with certainties, he shall end in doubts.",
      "Some books are to be tasted, others to be swallowed, and some few to be chewed and digested.",
      "Nature, to be commanded, must be obeyed.",
    ],
    gutenbergIds: [5500, 45988],
    form: "essay",
    keyWorks: ["Essays", "Novum Organum", "The Advancement of Learning"],
  },
  {
    id: "locke",
    name: "John Locke",
    school: "empiricism",
    era: "early-modern",
    birthYear: 1632,
    deathYear: 1704,
    nationality: "English",
    bio: "Physician and political adviser whose 'Essay Concerning Human Understanding' (1689) is the founding text of British empiricism, and whose 'Two Treatises of Government' (1689) supplied the philosophical vocabulary of the American and French Revolutions.",
    keyTakeaways: [
      "The mind at birth is a tabula rasa — a blank slate written on by experience.",
      "All ideas come from one of two sources: sensation (from the outer world) or reflection (from the mind's own operations).",
      "Personal identity through time consists in continuity of memory, not in the persistence of a soul-substance.",
      "Government's legitimate purpose is to protect natural rights to life, liberty, and property.",
      "Authority that violates the rights it was constituted to protect may be rightly resisted by the people.",
    ],
    takeawayPrompts: [
      "The mind is a blank slate, written on by experience.",
      "Government derives its just powers from the consent of the governed.",
      "All knowledge begins with sensation and reflection.",
      "Personal identity consists in continuity of memory.",
      "Where law ends, tyranny begins.",
    ],
    gutenbergIds: [7370, 10615, 7525],
    form: "treatise",
    keyWorks: [
      "Essay Concerning Human Understanding",
      "Two Treatises of Government",
      "A Letter Concerning Toleration",
    ],
  },
  {
    id: "berkeley",
    name: "George Berkeley",
    school: "empiricism",
    era: "early-modern",
    birthYear: 1685,
    deathYear: 1753,
    nationality: "Irish (Anglo-Irish)",
    bio: "Anglican bishop of Cloyne who pushed empiricism to its idealist conclusion: only minds and ideas exist; matter, as commonly conceived, is incoherent. Briefly raised money for a college in Bermuda; the lecture theatre at UC Berkeley is named for him.",
    keyTakeaways: [
      "To be is to be perceived (esse est percipi) — things exist only as ideas in some mind.",
      "There is no such thing as 'matter' apart from the qualities we perceive; the very concept is incoherent.",
      "When no human perceives a thing, it continues to exist because God perceives it.",
      "What we call laws of nature are regularities in God's ideas — not the workings of mind-independent matter.",
    ],
    takeawayPrompts: [
      "To be is to be perceived.",
      "There is no such thing as matter independent of mind.",
      "When no one is looking, God is.",
      "We have first raised a dust and then complain we cannot see.",
    ],
    gutenbergIds: [4723, 4724],
    form: "dialogue",
    keyWorks: [
      "A Treatise Concerning the Principles of Human Knowledge",
      "Three Dialogues Between Hylas and Philonous",
    ],
  },
  {
    id: "hume",
    name: "David Hume",
    school: "empiricism",
    era: "enlightenment",
    birthYear: 1711,
    deathYear: 1776,
    nationality: "Scottish",
    bio: "Edinburgh philosopher whose 'Treatise of Human Nature' (1739) was, in his words, 'stillborn from the press' and whose later essays and 'Enquiries' eventually made him the most influential empiricist in the history of philosophy. Cheerful atheist; died with great equanimity.",
    keyTakeaways: [
      "We never observe causation directly — we only see one event followed by another, and infer the connection from custom.",
      "Reason is, and ought only to be, the slave of the passions.",
      "The self is not a substance — it is a bundle of perceptions in constant flux.",
      "You cannot derive an 'ought' from an 'is': no purely factual statement entails a moral conclusion.",
      "No testimony for a miracle is ever weighty enough to outweigh the uniform experience that establishes the laws of nature.",
    ],
    takeawayPrompts: [
      "Reason is, and ought only to be, the slave of the passions.",
      "You cannot derive an 'ought' from an 'is'.",
      "We have no impression of causation — only one thing following another.",
      "The self is a bundle of perceptions.",
      "A wise man proportions his belief to the evidence.",
    ],
    gutenbergIds: [4320, 9662, 36120, 59792],
    form: "treatise",
    keyWorks: [
      "A Treatise of Human Nature",
      "An Enquiry Concerning Human Understanding",
      "Dialogues Concerning Natural Religion",
    ],
  },

  // ============ Political Liberalism ============
  {
    id: "hobbes",
    name: "Thomas Hobbes",
    school: "political-liberalism",
    era: "early-modern",
    birthYear: 1588,
    deathYear: 1679,
    nationality: "English",
    bio: "Translator of Thucydides and tutor to the future Charles II, who fled to Paris during the English Civil War and there wrote 'Leviathan' — the founding text of modern absolutism, in which a rational covenant constitutes the state.",
    keyTakeaways: [
      "In the state of nature there is a war of all against all, and life is solitary, poor, nasty, brutish, and short.",
      "Self-preservation is the fundamental right; everything else in politics derives from it.",
      "Rational individuals trade their natural liberty for security by covenanting to obey a sovereign.",
      "The sovereign must be undivided and absolute — divided sovereignty leads back to civil war.",
      "Without a common power to keep them in awe, men are in continual fear and danger of violent death.",
    ],
    takeawayPrompts: [
      "Life in the state of nature is solitary, poor, nasty, brutish, and short.",
      "The condition of man is a condition of war of every one against every one.",
      "Covenants without the sword are but words.",
      "There is no such thing as a divided sovereignty.",
    ],
    gutenbergIds: [3207],
    form: "treatise",
    keyWorks: ["Leviathan", "De Cive"],
  },
  {
    id: "rousseau",
    name: "Jean-Jacques Rousseau",
    school: "political-liberalism",
    era: "enlightenment",
    birthYear: 1712,
    deathYear: 1778,
    nationality: "Genevan-French",
    bio: "Self-taught Genevan watchmaker's son turned Parisian celebrity, whose paradoxical Enlightenment critiques of the Enlightenment shaped Romanticism, modern democracy, and modern educational theory. Wrote the first modern autobiography and one of the first epistolary best-sellers.",
    keyTakeaways: [
      "Man is born free, and everywhere he is in chains.",
      "Civilisation has corrupted natural human virtue — we were happier and freer in the state of nature.",
      "Legitimate political authority rests on the 'general will' of a self-governing people, not on inheritance or force.",
      "Education should follow the child's nature, not impose adult abstractions on it.",
      "Property, inequality, and the social hierarchies that flow from them are the source of most human misery.",
    ],
    takeawayPrompts: [
      "Man is born free, and everywhere he is in chains.",
      "Legitimate authority expresses the general will of the people.",
      "Civilisation has corrupted natural human goodness.",
      "The first man who, having fenced in a piece of land, said 'this is mine' — was the true founder of civil society.",
      "Education should follow the child's nature.",
    ],
    gutenbergIds: [46333],
    form: "treatise",
    keyWorks: [
      "The Social Contract",
      "Émile",
      "Discourse on the Origin of Inequality",
      "Confessions",
    ],
  },
  {
    id: "smith",
    name: "Adam Smith",
    school: "political-liberalism",
    era: "enlightenment",
    birthYear: 1723,
    deathYear: 1790,
    nationality: "Scottish",
    bio: "Glasgow moral philosopher whose two great works — 'The Theory of Moral Sentiments' (1759) and 'The Wealth of Nations' (1776) — between them founded modern moral psychology and modern economics.",
    keyTakeaways: [
      "Morality rests on sympathy: we judge our own conduct by imagining how an impartial spectator would view it.",
      "In a market economy, individuals pursuing their own interests are led 'as if by an invisible hand' to promote the public good.",
      "The division of labour, more than anything else, multiplies productive power.",
      "Government has three legitimate functions: defence, justice, and certain public works the market will not provide.",
      "Wealth is not gold or trade balances — it is the productive labour of a nation.",
    ],
    takeawayPrompts: [
      "It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner.",
      "Individuals pursuing self-interest are led, as if by an invisible hand, to promote the public good.",
      "The division of labour is the single greatest source of productive power.",
      "We judge ourselves by imagining how an impartial spectator would view us.",
    ],
    gutenbergIds: [3300, 58559, 38194],
    form: "treatise",
    keyWorks: ["The Wealth of Nations", "The Theory of Moral Sentiments"],
  },
  {
    id: "burke",
    name: "Edmund Burke",
    school: "political-liberalism",
    era: "enlightenment",
    birthYear: 1729,
    deathYear: 1797,
    nationality: "Anglo-Irish",
    bio: "Whig politician and political philosopher whose 'Reflections on the Revolution in France' (1790) gave conservatism its first systematic philosophical statement — a year before the revolution turned to terror, vindicating his alarm.",
    keyTakeaways: [
      "Society is a contract — but one between the dead, the living, and the unborn.",
      "Inherited institutions embody a prudence no individual lifetime can match; abstract reason is a poor substitute.",
      "All change should be cautious, gradual, and respectful of the existing fabric of social life.",
      "The rights of man do not exist as Platonic absolutes — they emerge from particular traditions, properly tended.",
      "Bad men need nothing more to compass their ends than that good men should look on and do nothing.",
    ],
    takeawayPrompts: [
      "Society is a contract between the dead, the living, and the unborn.",
      "All that is necessary for evil to triumph is for good men to do nothing.",
      "A state without the means of some change is without the means of its conservation.",
      "Custom reconciles us to everything.",
    ],
    gutenbergIds: [15700],
    form: "essay",
    keyWorks: [
      "Reflections on the Revolution in France",
      "A Philosophical Enquiry into the Origin of Our Ideas of the Sublime and Beautiful",
    ],
  },
  {
    id: "wollstonecraft",
    name: "Mary Wollstonecraft",
    school: "political-liberalism",
    era: "enlightenment",
    birthYear: 1759,
    deathYear: 1797,
    nationality: "English",
    bio: "Self-taught English writer who founded modern feminist philosophy with 'A Vindication of the Rights of Woman' (1792). Died at thirty-eight from complications of childbirth — the daughter she bore was Mary Shelley.",
    keyTakeaways: [
      "The rights of man are empty until they are also the rights of woman.",
      "Women are not naturally weak or frivolous — they are made so by an education that systematically denies them reason.",
      "Marriage as currently constituted is a kind of legal prostitution; only equality can ground genuine love.",
      "Civic virtue is impossible without equality between the sexes.",
      "Reason is no respecter of gender: cultivate it equally in girls, and the result will be equally rational adults.",
    ],
    takeawayPrompts: [
      "The rights of man are empty until they include the rights of woman.",
      "I do not wish women to have power over men; but over themselves.",
      "Women's apparent weakness is the product of their education, not their nature.",
      "Marriage will never be held sacred till women are educated and equal.",
    ],
    gutenbergIds: [3420],
    form: "treatise",
    keyWorks: [
      "A Vindication of the Rights of Woman",
      "A Vindication of the Rights of Men",
    ],
  },
  {
    id: "voltaire",
    name: "Voltaire",
    school: "political-liberalism",
    era: "enlightenment",
    birthYear: 1694,
    deathYear: 1778,
    nationality: "French",
    bio: "The Enlightenment's most quoted figure — playwright, historian, satirist, deist, and ferocious defender of religious toleration. Spent his last decades at Ferney, writing letters to most of literate Europe and intervening in famous cases of religious persecution.",
    keyTakeaways: [
      "If God did not exist, it would be necessary to invent him — religion is socially useful, but the specifics are mostly fraud.",
      "Tend your own garden — withdraw from the metaphysical noise and do the work in front of you.",
      "I disapprove of what you say, but I will defend to the death your right to say it.",
      "Common sense is not so common.",
      "Optimism is the mania for saying things are well when one is in hell.",
    ],
    takeawayPrompts: [
      "If God did not exist, it would be necessary to invent him.",
      "We must tend our own garden.",
      "Common sense is not so common.",
      "Optimism is the mania for saying things are well when one is in hell.",
    ],
    gutenbergIds: [19942],
    form: "essay",
    keyWorks: [
      "Candide",
      "Philosophical Dictionary",
      "Treatise on Tolerance",
    ],
  },

  // ============ German Idealism ============
  {
    id: "kant",
    name: "Immanuel Kant",
    school: "german-idealism",
    era: "enlightenment",
    birthYear: 1724,
    deathYear: 1804,
    nationality: "German (Prussian)",
    bio: "Königsberg professor whose punctuality was so reliable that neighbours set their watches by his daily walk. Spent decades on routine teaching, then between fifty-seven and seventy-six produced the three Critiques and reshaped Western philosophy.",
    keyTakeaways: [
      "The mind imposes the categories of space, time, and causation on experience — we therefore cannot know things as they are in themselves, only as they appear.",
      "Act only on that maxim by which you can at the same time will it to be a universal law.",
      "Always treat humanity, in yourself and in others, as an end and never merely as a means.",
      "Two things fill the mind with ever new wonder: the starry heavens above and the moral law within.",
      "Enlightenment is the human being's emergence from his self-incurred minority — dare to know (sapere aude).",
    ],
    takeawayPrompts: [
      "Act only on that maxim by which you can at the same time will it to be a universal law.",
      "Treat humanity, in yourself and others, always as an end and never merely as a means.",
      "Two things fill the mind with ever new wonder: the starry heavens above me and the moral law within me.",
      "Dare to know — Sapere aude.",
      "We can never know things as they are in themselves, only as they appear to us.",
    ],
    gutenbergIds: [4280, 5682, 5683, 6342],
    form: "treatise",
    keyWorks: [
      "Critique of Pure Reason",
      "Critique of Practical Reason",
      "Groundwork of the Metaphysics of Morals",
      "Critique of Judgment",
    ],
  },
  {
    id: "hegel",
    name: "G. W. F. Hegel",
    school: "german-idealism",
    era: "19th-century",
    birthYear: 1770,
    deathYear: 1831,
    nationality: "German",
    bio: "Berlin professor whose vast system — phenomenology, logic, philosophy of nature, philosophy of spirit, philosophy of history — claimed to be the philosophical articulation of how Spirit (Geist) comes progressively to know itself. Polarising in his own day and still polarising now.",
    keyTakeaways: [
      "The real is rational, and the rational is real — reality is intelligible all the way down.",
      "History is the progressive self-realisation of Spirit (Geist), advancing through dialectical contradiction.",
      "Every position generates its opposite; their conflict produces a higher synthesis that preserves and transcends both (Aufhebung).",
      "Freedom is not absence of constraint but conscious participation in a rational community.",
      "The owl of Minerva flies only at dusk — philosophy understands an age only as it ends.",
    ],
    takeawayPrompts: [
      "The real is rational, and the rational is real.",
      "History is the progressive self-realisation of Spirit.",
      "The owl of Minerva flies only at dusk.",
      "Every thesis generates its antithesis, and their tension a higher synthesis.",
      "Freedom is conscious participation in a rational community.",
    ],
    gutenbergIds: [55108, 51635],
    form: "treatise",
    keyWorks: [
      "Phenomenology of Spirit",
      "Science of Logic",
      "Philosophy of Right",
      "Lectures on the Philosophy of History",
    ],
  },
  {
    id: "schopenhauer",
    name: "Arthur Schopenhauer",
    school: "german-idealism",
    era: "19th-century",
    birthYear: 1788,
    deathYear: 1860,
    nationality: "German",
    bio: "A self-described loyal Kantian who detested Hegel and lived for decades in obscurity before late fame swept over him. Argued that behind the world of appearance lies not Spirit but a blind, striving Will — and that suffering is therefore the basic structure of existence.",
    keyTakeaways: [
      "The world is my representation — but behind appearance lies a single blind Will, of which everything is a manifestation.",
      "Life swings between suffering (when desire is unsatisfied) and boredom (when it is) — happiness is only the temporary cessation of pain.",
      "Compassion is the foundation of morality: it sees through the illusion of separate selves to the underlying unity of all that wills.",
      "Aesthetic experience and ascetic renunciation are the two paths to temporary release from the Will's tyranny.",
      "The history of the world is the history of suffering — better never to have been born.",
    ],
    takeawayPrompts: [
      "The world is my representation.",
      "Life swings like a pendulum between suffering and boredom.",
      "Compassion is the foundation of morality.",
      "Talent hits a target no one else can hit; genius hits a target no one else can see.",
      "Better never to have been born.",
    ],
    gutenbergIds: [10732, 38427, 40868, 44929],
    form: "essay",
    keyWorks: [
      "The World as Will and Representation",
      "On the Suffering of the World",
      "Parerga and Paralipomena",
    ],
  },

  // ============ Utilitarianism ============
  {
    id: "bentham",
    name: "Jeremy Bentham",
    school: "utilitarianism",
    era: "enlightenment",
    birthYear: 1748,
    deathYear: 1832,
    nationality: "English",
    bio: "English legal philosopher and reformer who founded utilitarianism, designed the Panopticon, drafted countless legal codes, and instructed in his will that his body be preserved and displayed at University College London — where it still sits, in a glass case, to this day.",
    keyTakeaways: [
      "The right action is the one that produces the greatest happiness for the greatest number.",
      "Pleasure and pain are the only motivations of human conduct — and the only standards of right and wrong.",
      "Natural rights are 'nonsense upon stilts' — rights exist only as creations of law, justified by their utility.",
      "Each is to count for one, and none for more than one — utilitarianism is radically egalitarian.",
      "The question is not 'can they reason?' nor 'can they talk?' but 'can they suffer?' — animals matter morally because they can.",
    ],
    takeawayPrompts: [
      "The greatest happiness of the greatest number is the foundation of morals and legislation.",
      "Natural rights are nonsense upon stilts.",
      "Each is to count for one, and none for more than one.",
      "The question is not, can they reason? nor, can they talk? but, can they suffer?",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: [
      "An Introduction to the Principles of Morals and Legislation",
      "A Fragment on Government",
    ],
  },
  {
    id: "mill",
    name: "John Stuart Mill",
    school: "utilitarianism",
    era: "19th-century",
    birthYear: 1806,
    deathYear: 1873,
    nationality: "English",
    bio: "Educated by his father from age three as an experiment in producing a utilitarian prodigy — Greek at three, Latin at seven, full mental breakdown at twenty. Recovered to become the most influential English-language philosopher of his century, defender of liberty, women's suffrage, and a refined utilitarianism that distinguished higher from lower pleasures.",
    keyTakeaways: [
      "The only purpose for which power can rightfully be exercised over any member of a civilised community, against his will, is to prevent harm to others.",
      "It is better to be Socrates dissatisfied than a pig satisfied — not all pleasures are equal.",
      "Liberty of thought and discussion is necessary even when the dissenting opinion is wrong: truth gains by being challenged.",
      "Women's subjection is not the result of nature but of millennia of legally enforced disadvantage; the case for equality is overwhelming.",
      "Individuality is itself a component of happiness — a life one has not chosen is barely worth calling one's own.",
    ],
    takeawayPrompts: [
      "Over himself, over his own body and mind, the individual is sovereign.",
      "It is better to be Socrates dissatisfied than a pig satisfied.",
      "If all mankind minus one were of one opinion, they would have no more right to silence that one person than he would to silence them.",
      "The legal subordination of one sex to the other is wrong in itself.",
      "The only freedom which deserves the name is that of pursuing our own good in our own way.",
    ],
    gutenbergIds: [5669, 11224, 10378],
    form: "essay",
    keyWorks: [
      "On Liberty",
      "Utilitarianism",
      "The Subjection of Women",
      "Autobiography",
    ],
  },

  // ============ Marxism ============
  {
    id: "marx",
    name: "Karl Marx",
    school: "marxism",
    era: "19th-century",
    birthYear: 1818,
    deathYear: 1883,
    nationality: "German (Prussian)",
    bio: "Trier-born, Hegel-trained, exiled to Paris and then London, where he spent decades in the British Museum reading room writing a critique of political economy that did more to shape the twentieth century than any other body of thought. Lived in poverty supported by Engels.",
    keyTakeaways: [
      "The history of all hitherto existing society is the history of class struggles.",
      "Capitalism extracts surplus value from labour, concentrates capital, and generates the very proletariat that will eventually overthrow it.",
      "Religion is the sigh of the oppressed creature, the heart of a heartless world — the opium of the people.",
      "Workers of the world, unite — you have nothing to lose but your chains.",
      "The philosophers have only interpreted the world, in various ways; the point, however, is to change it.",
    ],
    takeawayPrompts: [
      "Workers of the world, unite — you have nothing to lose but your chains.",
      "Religion is the opium of the people.",
      "The philosophers have only interpreted the world; the point is to change it.",
      "The history of all hitherto existing society is the history of class struggles.",
      "From each according to his ability, to each according to his needs.",
    ],
    gutenbergIds: [61],
    form: "treatise",
    keyWorks: [
      "The Communist Manifesto",
      "Capital, Volume I",
      "The German Ideology",
      "Economic and Philosophic Manuscripts of 1844",
    ],
  },

  // ============ Pragmatism ============
  {
    id: "peirce",
    name: "Charles Sanders Peirce",
    school: "pragmatism",
    era: "19th-century",
    birthYear: 1839,
    deathYear: 1914,
    nationality: "American",
    bio: "Brilliant, mercurial, perpetually broke American philosopher and logician who founded pragmatism, formalised semiotics, and was largely shut out of academia for personal reasons. Most of his enormous output was unpublished until decades after his death.",
    keyTakeaways: [
      "To clarify an idea, work out what practical effects you would expect if it were true — those effects are the whole of the idea's meaning.",
      "Truth is the opinion fated to be agreed upon by all who investigate, in the long run.",
      "There are three irreducible categories: firstness (quality), secondness (reaction), and thirdness (mediation).",
      "Beliefs are settled by four methods — tenacity, authority, a priori reasoning, and inquiry — and only the last is reliable.",
      "Inquiry begins with genuine doubt, not Cartesian play-doubt; and ends only when belief is re-established.",
    ],
    takeawayPrompts: [
      "Consider what effects, that might conceivably have practical bearings, you conceive the object of your conception to have. Then your conception of those effects is the whole of your conception of the object.",
      "Truth is the opinion fated to be agreed upon by all who investigate.",
      "We cannot begin with complete doubt.",
      "Inquiry begins with real doubt, not paper-doubt.",
    ],
    gutenbergIds: [],
    form: "essay",
    keyWorks: [
      "How to Make Our Ideas Clear",
      "The Fixation of Belief",
      "Collected Papers",
    ],
  },
  {
    id: "william-james",
    name: "William James",
    school: "pragmatism",
    era: "19th-century",
    birthYear: 1842,
    deathYear: 1910,
    nationality: "American",
    bio: "Harvard physician, psychologist, and philosopher — older brother of Henry James the novelist — who turned Peirce's technical pragmatism into a popular philosophical movement and wrote the founding text of American psychology along the way.",
    keyTakeaways: [
      "Truth is what works — what 'pays its way' in the conduct of life.",
      "We are entitled to believe ahead of the evidence when the option is live, forced, and momentous — the 'will to believe.'",
      "Consciousness is a stream, not a chain — thoughts flow continuously, not in discrete units.",
      "Religious experience deserves serious attention as data, regardless of its metaphysical status.",
      "The world is genuinely open — a 'pluralistic universe' in the making, not a finished block.",
    ],
    takeawayPrompts: [
      "Truth is what works.",
      "Faith in a fact can help create the fact.",
      "Consciousness is a stream, not a chain.",
      "We are entitled to believe ahead of the evidence when the option is live, forced, and momentous.",
      "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.",
    ],
    gutenbergIds: [5116, 5827, 11984, 26659],
    form: "essay",
    keyWorks: [
      "The Varieties of Religious Experience",
      "Pragmatism",
      "The Principles of Psychology",
      "The Will to Believe",
    ],
  },
  {
    id: "dewey",
    name: "John Dewey",
    school: "pragmatism",
    era: "20th-century",
    birthYear: 1859,
    deathYear: 1952,
    nationality: "American",
    bio: "Vermont-born educator who taught at Michigan, Chicago, and Columbia, founded the laboratory school that bore his name, and shaped American progressive education more than any other figure. His pragmatism stressed inquiry, democracy, and the continuous reconstruction of experience.",
    keyTakeaways: [
      "Thought is a tool for solving problems, not a mirror reflecting an antecedent reality.",
      "Education is not preparation for life — it is life itself.",
      "Democracy is more than a form of government; it is a mode of associated living, of conjoint communicated experience.",
      "The end of inquiry is not certainty but warranted assertibility — beliefs that have survived testing.",
      "We do not learn from experience; we learn from reflecting on experience.",
    ],
    takeawayPrompts: [
      "Education is not preparation for life; education is life itself.",
      "Democracy is a mode of associated living, of conjoint communicated experience.",
      "We do not learn from experience; we learn from reflecting on experience.",
      "The aim of education is to enable individuals to continue their education.",
    ],
    gutenbergIds: [852],
    form: "treatise",
    keyWorks: [
      "Democracy and Education",
      "Experience and Nature",
      "Reconstruction in Philosophy",
      "How We Think",
    ],
  },

  // ============ Existentialism ============
  {
    id: "kierkegaard",
    name: "Søren Kierkegaard",
    school: "existentialism",
    era: "19th-century",
    birthYear: 1813,
    deathYear: 1855,
    nationality: "Danish",
    bio: "Eccentric Copenhagen aesthete and theologian who broke off his engagement to Regine Olsen, attacked the Danish state church, and wrote under a fleet of pseudonyms a series of brilliant, contradictory, irreducibly individual works that became, in retrospect, the founding documents of existentialism.",
    keyTakeaways: [
      "Truth is subjectivity — the question is not what to believe but how to believe.",
      "There are three stages of existence: the aesthetic (pleasure), the ethical (duty), and the religious (faith).",
      "Faith requires a 'leap' beyond reason — Abraham raising the knife over Isaac is faith's terrifying image.",
      "Anxiety is the dizziness of freedom — the price of being a self.",
      "The crowd is untruth; only the individual stands before God.",
    ],
    takeawayPrompts: [
      "Truth is subjectivity.",
      "Anxiety is the dizziness of freedom.",
      "Life can only be understood backwards, but it must be lived forwards.",
      "The crowd is untruth.",
      "Faith is the highest passion in a human being.",
    ],
    gutenbergIds: [],
    form: "essay",
    keyWorks: [
      "Either/Or",
      "Fear and Trembling",
      "The Sickness Unto Death",
      "Concluding Unscientific Postscript",
    ],
  },
  {
    id: "nietzsche",
    name: "Friedrich Nietzsche",
    school: "existentialism",
    era: "19th-century",
    birthYear: 1844,
    deathYear: 1900,
    nationality: "German",
    bio: "Brilliant young professor of philology at Basel who broke down at thirty-five, retired to write the books that would make him famous, collapsed in Turin at forty-five embracing a horse, and spent the last decade of his life under his sister's care, insane.",
    keyTakeaways: [
      "God is dead — and we have killed him; we must now create our own values or sink into nihilism.",
      "Christianity is a slave morality that inverted the natural order, making weakness, meekness, and pity into virtues.",
      "The will to power, not pleasure, is the fundamental human drive.",
      "Live as if you would have to live this same life over again, identically, eternally — and want it.",
      "Become who you are: the goal is not happiness or virtue but the self-overcoming of the human into the Übermensch.",
    ],
    takeawayPrompts: [
      "God is dead — and we have killed him.",
      "What does not kill me makes me stronger.",
      "Live as if you would have to live every moment again, eternally.",
      "Become who you are.",
      "He who has a why to live for can bear almost any how.",
      "Christianity is a slave morality.",
    ],
    gutenbergIds: [4363, 19322, 38145, 1998, 52263, 51548],
    form: "aphorism",
    keyWorks: [
      "Thus Spoke Zarathustra",
      "Beyond Good and Evil",
      "On the Genealogy of Morality",
      "Twilight of the Idols",
      "The Birth of Tragedy",
    ],
  },
  {
    id: "sartre",
    name: "Jean-Paul Sartre",
    school: "existentialism",
    era: "20th-century",
    birthYear: 1905,
    deathYear: 1980,
    nationality: "French",
    bio: "Paris-born public intellectual, novelist, playwright, and lifelong companion of Simone de Beauvoir, who in the late 1940s made existentialism the most fashionable philosophy in Europe — and later declined the Nobel Prize on the grounds that no writer should be turned into an institution.",
    keyTakeaways: [
      "Existence precedes essence: there is no human nature; we make ourselves through our choices.",
      "We are condemned to be free — there is no escape from the responsibility of choosing.",
      "Bad faith is the lie we tell ourselves to deny our freedom — pretending we 'had to' do what we chose.",
      "Hell is other people — the gaze of the other turns me into an object I do not control.",
      "Man is nothing else but what he makes of himself.",
    ],
    takeawayPrompts: [
      "Existence precedes essence.",
      "Man is condemned to be free.",
      "Hell is other people.",
      "We are our choices.",
      "Man is nothing else but what he makes of himself.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: [
      "Being and Nothingness",
      "Existentialism is a Humanism",
      "Nausea",
      "No Exit",
    ],
  },
  {
    id: "camus",
    name: "Albert Camus",
    school: "existentialism",
    era: "20th-century",
    birthYear: 1913,
    deathYear: 1960,
    nationality: "French-Algerian",
    bio: "Pied-noir son of an illiterate cleaning woman who rose to win the Nobel Prize at forty-four. Resistance journalist, novelist, and absurdist philosopher who insisted, against Sartre, that he was not an existentialist. Killed in a car crash at forty-six with an unused train ticket in his pocket.",
    keyTakeaways: [
      "There is only one truly serious philosophical problem, and that is suicide — does life, with no inherent meaning, deserve to be lived?",
      "The absurd is the confrontation between the human demand for meaning and the universe's silence.",
      "We must imagine Sisyphus happy: pushing the rock is enough; the struggle itself fills a man's heart.",
      "Revolt against the absurd, not in metaphysical anguish but in lucid, ongoing, fully aware living.",
      "Solidarity with other humans — in plague, in occupation, in any crisis — is the only honest ethical response to the absurd.",
    ],
    takeawayPrompts: [
      "One must imagine Sisyphus happy.",
      "There is but one truly serious philosophical problem, and that is suicide.",
      "I rebel — therefore we exist.",
      "In the depth of winter, I finally learned that there was in me an invincible summer.",
      "The struggle itself toward the heights is enough to fill a man's heart.",
    ],
    gutenbergIds: [],
    form: "essay",
    keyWorks: [
      "The Myth of Sisyphus",
      "The Stranger",
      "The Plague",
      "The Rebel",
    ],
  },
  {
    id: "de-beauvoir",
    name: "Simone de Beauvoir",
    school: "existentialism",
    era: "20th-century",
    birthYear: 1908,
    deathYear: 1986,
    nationality: "French",
    bio: "Sorbonne-trained philosopher and lifelong intellectual partner of Sartre, whose 'The Second Sex' (1949) reset feminist philosophy on existentialist foundations and remains the most influential single work of 20th-century feminist thought.",
    keyTakeaways: [
      "One is not born, but rather becomes, a woman — gender is socially constructed.",
      "Woman has been defined throughout history as 'the Other' — Man as the absolute, woman as the relative.",
      "Authentic freedom requires that we will the freedom of others, since our own freedom can only exist in a free world.",
      "Femininity is not a destiny: women's situation is changeable, and the project of changing it is properly philosophical.",
      "To be free is to be in a state of permanent ethical demand — there is no rest in liberation.",
    ],
    takeawayPrompts: [
      "One is not born, but rather becomes, a woman.",
      "Woman is the Other.",
      "To be free is to will the freedom of others.",
      "Change your life today. Don't gamble on the future, act now, without delay.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: [
      "The Second Sex",
      "The Ethics of Ambiguity",
      "Memoirs of a Dutiful Daughter",
    ],
  },

  // ============ Phenomenology ============
  {
    id: "husserl",
    name: "Edmund Husserl",
    school: "phenomenology",
    era: "20th-century",
    birthYear: 1859,
    deathYear: 1938,
    nationality: "German (Moravian-born)",
    bio: "Mathematician who turned to philosophy under Brentano and founded the phenomenological movement. Spent decades developing the method that would, through his student Heidegger, dominate 20th-century continental philosophy. Was barred from his Freiburg office by the Nazis at the end of his life.",
    keyTakeaways: [
      "Phenomenology returns 'to the things themselves' — describe what is given in conscious experience before any theory.",
      "Bracket the question of whether the external world exists (the phenomenological epoché) and describe how it shows up for consciousness.",
      "All consciousness is intentional — it is always consciousness of something.",
      "The lifeworld — the pre-scientific world of everyday experience — is the ground that all scientific abstraction presupposes.",
    ],
    takeawayPrompts: [
      "To the things themselves.",
      "All consciousness is consciousness of something.",
      "Bracket the world and describe how it shows up for consciousness.",
      "The crisis of European science is the forgetting of the lifeworld.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: [
      "Logical Investigations",
      "Ideas: General Introduction to a Pure Phenomenology",
      "The Crisis of European Sciences and Transcendental Phenomenology",
    ],
  },
  {
    id: "heidegger",
    name: "Martin Heidegger",
    school: "phenomenology",
    era: "20th-century",
    birthYear: 1889,
    deathYear: 1976,
    nationality: "German",
    bio: "Husserl's student and successor at Freiburg, whose 'Being and Time' (1927) reset the agenda of continental philosophy. Joined the Nazi Party in 1933 and served as rector of Freiburg; the relation between his philosophy and his politics remains a permanent open wound.",
    keyTakeaways: [
      "The fundamental question of philosophy is the question of Being — what does it mean for anything to be at all?",
      "Dasein — the being whose own being is a question for it — is thrown into a world, oriented by mood and care.",
      "Authentic existence requires confronting one's being-toward-death and choosing one's own possibilities, rather than fleeing into the average everyday.",
      "Modern technology is not a neutral tool but a way of revealing the world that turns everything, including humans, into standing reserve.",
      "Language is the house of Being — poetry can disclose what calculative thinking conceals.",
    ],
    takeawayPrompts: [
      "Why is there something rather than nothing?",
      "Dasein is being-toward-death.",
      "Language is the house of Being.",
      "Modern technology enframes everything as standing reserve.",
      "Only a god can save us now.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: [
      "Being and Time",
      "The Question Concerning Technology",
      "What Is Called Thinking?",
    ],
  },
  {
    id: "merleau-ponty",
    name: "Maurice Merleau-Ponty",
    school: "phenomenology",
    era: "20th-century",
    birthYear: 1908,
    deathYear: 1961,
    nationality: "French",
    bio: "French phenomenologist who, against Sartre's intellectualist consciousness, returned the body to the centre of philosophical attention. His 'Phenomenology of Perception' (1945) is the founding text of embodied cognition.",
    keyTakeaways: [
      "Perception is not a representation in a mind but the body's primary engagement with the world.",
      "Consciousness is incarnate — there is no 'view from nowhere' separable from the lived body.",
      "The 'flesh' is the common element of perceiver and perceived, irreducible to subject or object.",
      "Painting, especially Cézanne, can show us how perception works as no description can.",
    ],
    takeawayPrompts: [
      "I am my body.",
      "Perception is not a representation in a mind, but the body's primary engagement with the world.",
      "Consciousness is incarnate.",
      "The world is what we perceive.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: [
      "Phenomenology of Perception",
      "The Visible and the Invisible",
      "The Structure of Behaviour",
    ],
  },

  // ============ Analytic Philosophy ============
  {
    id: "frege",
    name: "Gottlob Frege",
    school: "analytic",
    era: "19th-century",
    birthYear: 1848,
    deathYear: 1925,
    nationality: "German",
    bio: "Obscure Jena mathematics professor who, in 1879, invented modern predicate logic in a slim book ('Begriffsschrift') almost no one read. Russell's discovery of a paradox in his foundational system destroyed Frege's life's work, but his ideas became the foundation of analytic philosophy.",
    keyTakeaways: [
      "Sense and reference are distinct: 'the morning star' and 'the evening star' refer to the same planet but have different senses.",
      "Logic and arithmetic are objective — they are not psychological processes in human minds.",
      "Concepts are functions: a predicate is something that maps objects to truth-values.",
      "Numbers are not properties of things but of concepts — '4 horses' means 'the concept horse has four instances.'",
    ],
    takeawayPrompts: [
      "Sense and reference are distinct.",
      "Logic and arithmetic are objective, not psychological.",
      "A statement's truth-value is its reference; its sense is the way that truth-value is presented.",
      "Numbers are properties of concepts, not of things.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: [
      "Begriffsschrift",
      "The Foundations of Arithmetic",
      "On Sense and Reference",
    ],
  },
  {
    id: "russell",
    name: "Bertrand Russell",
    school: "analytic",
    era: "20th-century",
    birthYear: 1872,
    deathYear: 1970,
    nationality: "English",
    bio: "Aristocratic Cambridge logician, three times married, twice jailed for pacifism, who co-wrote 'Principia Mathematica' with Whitehead, almost won the Nobel for literature for his popular essays (he did, in 1950), and remained politically engaged into his nineties.",
    keyTakeaways: [
      "The grammatical form of a sentence can hide its logical form — careful analysis reveals what we are really saying.",
      "Definite descriptions ('the present king of France') can be analysed away, so we are not committed to mythical entities by talking about them.",
      "Knowledge by acquaintance (direct experience) is the foundation of knowledge by description (theoretical claims).",
      "Religion is largely based on fear, and fear is the parent of cruelty.",
      "The good life is one inspired by love and guided by knowledge.",
    ],
    takeawayPrompts: [
      "The good life is one inspired by love and guided by knowledge.",
      "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.",
      "War does not determine who is right — only who is left.",
      "I would never die for my beliefs because I might be wrong.",
      "To be without some of the things you want is an indispensable part of happiness.",
    ],
    gutenbergIds: [25447, 17350, 690, 44932, 5827],
    form: "essay",
    keyWorks: [
      "The Problems of Philosophy",
      "Principia Mathematica (with Whitehead)",
      "A History of Western Philosophy",
      "Why I Am Not a Christian",
    ],
  },
  {
    id: "wittgenstein",
    name: "Ludwig Wittgenstein",
    school: "analytic",
    era: "20th-century",
    birthYear: 1889,
    deathYear: 1951,
    nationality: "Austrian-British",
    bio: "Heir to one of Europe's largest fortunes, which he gave away. Russell's student, then his teacher; produced two utterly different masterpieces, fought in both world wars, taught village schoolchildren in the Austrian Alps, and is considered by many the most important philosopher of the twentieth century.",
    keyTakeaways: [
      "The limits of my language mean the limits of my world.",
      "Whereof one cannot speak, thereof one must be silent.",
      "The meaning of a word is its use in the language (later Wittgenstein).",
      "Philosophical problems arise when language goes on holiday — they are dissolved, not solved, by careful attention to ordinary use.",
      "There is no private language: meaning is essentially public, embedded in shared practices ('forms of life').",
    ],
    takeawayPrompts: [
      "The limits of my language mean the limits of my world.",
      "Whereof one cannot speak, thereof one must be silent.",
      "The meaning of a word is its use in the language.",
      "If a lion could talk, we could not understand him.",
      "Philosophy is a battle against the bewitchment of our intelligence by means of language.",
    ],
    gutenbergIds: [5740],
    form: "aphorism",
    keyWorks: [
      "Tractatus Logico-Philosophicus",
      "Philosophical Investigations",
      "On Certainty",
    ],
  },
  {
    id: "quine",
    name: "W. V. O. Quine",
    school: "analytic",
    era: "20th-century",
    birthYear: 1908,
    deathYear: 2000,
    nationality: "American",
    bio: "Harvard logician and philosopher who dominated mid-20th-century American philosophy and demolished the analytic/synthetic distinction that was a load-bearing wall of logical positivism, leaving a more naturalist successor.",
    keyTakeaways: [
      "There is no sharp line between analytic truths (true by definition) and synthetic truths (true by experience).",
      "Our beliefs face the tribunal of experience as a corporate body, not one by one.",
      "Translation between languages is radically indeterminate — there is no unique correct rendering.",
      "To be is to be the value of a bound variable: ontology is what our best theories quantify over.",
      "Philosophy is continuous with science — it is not a special discipline with its own privileged access to truth.",
    ],
    takeawayPrompts: [
      "To be is to be the value of a bound variable.",
      "Our beliefs face the tribunal of experience as a corporate body, not one by one.",
      "There is no sharp line between analytic and synthetic truths.",
      "Translation is radically indeterminate.",
    ],
    gutenbergIds: [],
    form: "essay",
    keyWorks: [
      "Two Dogmas of Empiricism",
      "Word and Object",
      "From a Logical Point of View",
    ],
  },
  {
    id: "rawls",
    name: "John Rawls",
    school: "analytic",
    era: "20th-century",
    birthYear: 1921,
    deathYear: 2002,
    nationality: "American",
    bio: "Harvard political philosopher whose 'A Theory of Justice' (1971) almost single-handedly revived English-language political philosophy after decades of analytic neglect. The 'original position' and 'veil of ignorance' became permanent fixtures of liberal political thought.",
    keyTakeaways: [
      "Principles of justice are those we would choose behind a 'veil of ignorance,' not knowing our own position in society.",
      "Each person has an equal right to the most extensive basic liberties compatible with similar liberties for all.",
      "Social and economic inequalities are justified only when they are arranged to be of greatest benefit to the least advantaged.",
      "Justice is the first virtue of social institutions, as truth is of systems of thought.",
    ],
    takeawayPrompts: [
      "Justice is the first virtue of social institutions, as truth is of systems of thought.",
      "Choose principles of justice from behind a veil of ignorance.",
      "Inequalities are justified only if they benefit the least advantaged.",
      "Each person possesses an inviolability founded on justice that even the welfare of society as a whole cannot override.",
    ],
    gutenbergIds: [],
    form: "treatise",
    keyWorks: ["A Theory of Justice", "Political Liberalism"],
  },
];

export function getThinkerById(id: string): Thinker | undefined {
  return THINKERS.find((t) => t.id === id);
}

export function getSchoolForThinker(thinker: Thinker): School | undefined {
  return getSchoolById(thinker.school);
}

export function getThinkersBySchool(schoolId: string): Thinker[] {
  return THINKERS.filter((t) => t.school === schoolId);
}

export function getThinkersByEra(era: Era): Thinker[] {
  return THINKERS.filter((t) => t.era === era);
}

export const ERAS: { id: Era; name: string }[] = [
  { id: "ancient", name: "Ancient" },
  { id: "medieval", name: "Medieval" },
  { id: "early-modern", name: "Early Modern" },
  { id: "enlightenment", name: "Enlightenment" },
  { id: "19th-century", name: "19th Century" },
  { id: "20th-century", name: "20th Century" },
];

// Re-export so consumers can pull both from one module if they want.
export { SCHOOLS, getSchoolById };
export type { School };
